# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class RenderedFaces(object):
    ONE = 0
    TWO = 1


class Stroke(object):
    DEFAULT = 0


class AxisPartClass(object):
    NONE = 0
    WIRE = 1
    WIRE_SET = 2
    CIRCLE_CURVE = 3


class RepresentationClass(object):
    NONE = 0
    SHELL = 1
    CIRCLE_EXTRUSION = 2


class ShellType(object):
    NONE = 0
    BIG = 1


class FloatVector(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 12

    # FloatVector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloatVector
    def X(self):
        return self._tab.Get(
            flatbuffers.number_types.Float32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0),
        )

    # FloatVector
    def Y(self):
        return self._tab.Get(
            flatbuffers.number_types.Float32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4),
        )

    # FloatVector
    def Z(self):
        return self._tab.Get(
            flatbuffers.number_types.Float32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8),
        )


def CreateFloatVector(builder, x, y, z):
    builder.Prep(4, 12)
    builder.PrependFloat32(z)
    builder.PrependFloat32(y)
    builder.PrependFloat32(x)
    return builder.Offset()


class DoubleVector(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 24

    # DoubleVector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DoubleVector
    def X(self):
        return self._tab.Get(
            flatbuffers.number_types.Float64Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0),
        )

    # DoubleVector
    def Y(self):
        return self._tab.Get(
            flatbuffers.number_types.Float64Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8),
        )

    # DoubleVector
    def Z(self):
        return self._tab.Get(
            flatbuffers.number_types.Float64Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16),
        )


def CreateDoubleVector(builder, x, y, z):
    builder.Prep(8, 24)
    builder.PrependFloat64(z)
    builder.PrependFloat64(y)
    builder.PrependFloat64(x)
    return builder.Offset()


class Transform(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 48

    # Transform
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Transform
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Transform
    def XDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj

    # Transform
    def YDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 36)
        return obj


def CreateTransform(
    builder,
    position_x,
    position_y,
    position_z,
    xDirection_x,
    xDirection_y,
    xDirection_z,
    yDirection_x,
    yDirection_y,
    yDirection_z,
):
    builder.Prep(8, 48)
    builder.Prep(4, 12)
    builder.PrependFloat32(yDirection_z)
    builder.PrependFloat32(yDirection_y)
    builder.PrependFloat32(yDirection_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(xDirection_z)
    builder.PrependFloat32(xDirection_y)
    builder.PrependFloat32(xDirection_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(position_z)
    builder.PrependFloat64(position_y)
    builder.PrependFloat64(position_x)
    return builder.Offset()


class Material(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 6

    # Material
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Material
    def R(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint8Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0),
        )

    # Material
    def G(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint8Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1),
        )

    # Material
    def B(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint8Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2),
        )

    # Material
    def A(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint8Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3),
        )

    # Material
    def RenderedFaces(self):
        return self._tab.Get(
            flatbuffers.number_types.Int8Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4),
        )

    # Material
    def Stroke(self):
        return self._tab.Get(
            flatbuffers.number_types.Int8Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(5),
        )


def CreateMaterial(builder, r, g, b, a, renderedFaces, stroke):
    builder.Prep(1, 6)
    builder.PrependInt8(stroke)
    builder.PrependInt8(renderedFaces)
    builder.PrependUint8(a)
    builder.PrependUint8(b)
    builder.PrependUint8(g)
    builder.PrependUint8(r)
    return builder.Offset()


class BoundingBox(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 24

    # BoundingBox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoundingBox
    def Min(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # BoundingBox
    def Max(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def CreateBoundingBox(builder, min_x, min_y, min_z, max_x, max_y, max_z):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependFloat32(max_z)
    builder.PrependFloat32(max_y)
    builder.PrependFloat32(max_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(min_z)
    builder.PrependFloat32(min_y)
    builder.PrependFloat32(min_x)
    return builder.Offset()


class Wire(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 24

    # Wire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Wire
    def P1(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Wire
    def P2(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def CreateWire(builder, p1_x, p1_y, p1_z, p2_x, p2_y, p2_z):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependFloat32(p2_z)
    builder.PrependFloat32(p2_y)
    builder.PrependFloat32(p2_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(p1_z)
    builder.PrependFloat32(p1_y)
    builder.PrependFloat32(p1_x)
    return builder.Offset()


class WireSet(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WireSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWireSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def WireSetBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # WireSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WireSet
    def Ps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = FloatVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WireSet
    def PsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WireSet
    def PsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def WireSetStart(builder):
    builder.StartObject(1)


def WireSetAddPs(builder, ps):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(ps), 0
    )


def WireSetStartPsVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)


def WireSetEnd(builder):
    return builder.EndObject()


class CircleCurve(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 44

    # CircleCurve
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CircleCurve
    def Aperture(self):
        return self._tab.Get(
            flatbuffers.number_types.Float32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0),
        )

    # CircleCurve
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # CircleCurve
    def Radius(self):
        return self._tab.Get(
            flatbuffers.number_types.Float32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16),
        )

    # CircleCurve
    def XDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 20)
        return obj

    # CircleCurve
    def YDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 32)
        return obj


def CreateCircleCurve(
    builder,
    aperture,
    position_x,
    position_y,
    position_z,
    radius,
    xDirection_x,
    xDirection_y,
    xDirection_z,
    yDirection_x,
    yDirection_y,
    yDirection_z,
):
    builder.Prep(4, 44)
    builder.Prep(4, 12)
    builder.PrependFloat32(yDirection_z)
    builder.PrependFloat32(yDirection_y)
    builder.PrependFloat32(yDirection_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(xDirection_z)
    builder.PrependFloat32(xDirection_y)
    builder.PrependFloat32(xDirection_x)
    builder.PrependFloat32(radius)
    builder.Prep(4, 12)
    builder.PrependFloat32(position_z)
    builder.PrependFloat32(position_y)
    builder.PrependFloat32(position_x)
    builder.PrependFloat32(aperture)
    return builder.Offset()


class ShellHole(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShellHole()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShellHole(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def ShellHoleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # ShellHole
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShellHole
    def Indices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2),
            )
        return 0

    # ShellHole
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ShellHole
    def IndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShellHole
    def IndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ShellHole
    def ProfileId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags, o + self._tab.Pos
            )
        return 0


def ShellHoleStart(builder):
    builder.StartObject(2)


def ShellHoleAddIndices(builder, indices):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0
    )


def ShellHoleStartIndicesVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)


def ShellHoleAddProfileId(builder, profileId):
    builder.PrependUint16Slot(1, profileId, 0)


def ShellHoleEnd(builder):
    return builder.EndObject()


class ShellProfile(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShellProfile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShellProfile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def ShellProfileBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # ShellProfile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShellProfile
    def Indices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2),
            )
        return 0

    # ShellProfile
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ShellProfile
    def IndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShellProfile
    def IndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def ShellProfileStart(builder):
    builder.StartObject(1)


def ShellProfileAddIndices(builder, indices):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0
    )


def ShellProfileStartIndicesVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)


def ShellProfileEnd(builder):
    return builder.EndObject()


class BigShellHole(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BigShellHole()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBigShellHole(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def BigShellHoleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # BigShellHole
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BigShellHole
    def Indices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # BigShellHole
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # BigShellHole
    def IndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BigShellHole
    def IndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # BigShellHole
    def ProfileId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags, o + self._tab.Pos
            )
        return 0


def BigShellHoleStart(builder):
    builder.StartObject(2)


def BigShellHoleAddIndices(builder, indices):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0
    )


def BigShellHoleStartIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def BigShellHoleAddProfileId(builder, profileId):
    builder.PrependUint16Slot(1, profileId, 0)


def BigShellHoleEnd(builder):
    return builder.EndObject()


class BigShellProfile(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BigShellProfile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBigShellProfile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def BigShellProfileBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # BigShellProfile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BigShellProfile
    def Indices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # BigShellProfile
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # BigShellProfile
    def IndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BigShellProfile
    def IndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def BigShellProfileStart(builder):
    builder.StartObject(1)


def BigShellProfileAddIndices(builder, indices):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0
    )


def BigShellProfileStartIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def BigShellProfileEnd(builder):
    return builder.EndObject()


class Axis(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Axis()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAxis(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def AxisBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # Axis
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Axis
    def Wires(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            obj = Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Axis
    def WiresLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def WiresIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Axis
    def Order(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Axis
    def OrderAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Axis
    def OrderLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def OrderIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Axis
    def Parts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Int8Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1),
            )
        return 0

    # Axis
    def PartsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Axis
    def PartsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def PartsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Axis
    def WireSets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = WireSet()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Axis
    def WireSetsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def WireSetsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Axis
    def CircleCurves(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 44
            obj = CircleCurve()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Axis
    def CircleCurvesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def CircleCurvesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0


def AxisStart(builder):
    builder.StartObject(5)


def AxisAddWires(builder, wires):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(wires), 0
    )


def AxisStartWiresVector(builder, numElems):
    return builder.StartVector(24, numElems, 4)


def AxisAddOrder(builder, order):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(order), 0
    )


def AxisStartOrderVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def AxisAddParts(builder, parts):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(parts), 0
    )


def AxisStartPartsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)


def AxisAddWireSets(builder, wireSets):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(wireSets), 0
    )


def AxisStartWireSetsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def AxisAddCircleCurves(builder, circleCurves):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(circleCurves), 0
    )


def AxisStartCircleCurvesVector(builder, numElems):
    return builder.StartVector(44, numElems, 4)


def AxisEnd(builder):
    return builder.EndObject()


class Representation(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 32

    # Representation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Representation
    def Id(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0),
        )

    # Representation
    def Bbox(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # Representation
    def RepresentationClass(self):
        return self._tab.Get(
            flatbuffers.number_types.Int8Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28),
        )


def CreateRepresentation(
    builder,
    id,
    bbox_min_x,
    bbox_min_y,
    bbox_min_z,
    bbox_max_x,
    bbox_max_y,
    bbox_max_z,
    representationClass,
):
    builder.Prep(4, 32)
    builder.Pad(3)
    builder.PrependInt8(representationClass)
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependFloat32(bbox_max_z)
    builder.PrependFloat32(bbox_max_y)
    builder.PrependFloat32(bbox_max_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(bbox_min_z)
    builder.PrependFloat32(bbox_min_y)
    builder.PrependFloat32(bbox_min_x)
    builder.PrependUint32(id)
    return builder.Offset()


class Sample(object):
    __slots__ = ["_tab"]

    @classmethod
    def SizeOf(cls):
        return 16

    # Sample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Sample
    def Item(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0),
        )

    # Sample
    def Material(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4),
        )

    # Sample
    def Representation(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8),
        )

    # Sample
    def LocalTransform(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint32Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12),
        )


def CreateSample(builder, item, material, representation, localTransform):
    builder.Prep(4, 16)
    builder.PrependUint32(localTransform)
    builder.PrependUint32(representation)
    builder.PrependUint32(material)
    builder.PrependUint32(item)
    return builder.Offset()


class Shell(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Shell()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShell(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def ShellBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # Shell
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Shell
    def Profiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ShellProfile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def ProfilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def ProfilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Shell
    def Holes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ShellHole()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def HolesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def HolesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Shell
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = FloatVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def PointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Shell
    def BigProfiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BigShellProfile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def BigProfilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def BigProfilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Shell
    def BigHoles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BigShellHole()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def BigHolesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def BigHolesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Shell
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Shell
    def ProfilesFaceIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2),
            )
        return 0

    # Shell
    def ProfilesFaceIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # Shell
    def ProfilesFaceIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def ProfilesFaceIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0


def ShellStart(builder):
    builder.StartObject(7)


def ShellAddProfiles(builder, profiles):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(profiles), 0
    )


def ShellStartProfilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ShellAddHoles(builder, holes):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(holes), 0
    )


def ShellStartHolesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ShellAddPoints(builder, points):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0
    )


def ShellStartPointsVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)


def ShellAddBigProfiles(builder, bigProfiles):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(bigProfiles), 0
    )


def ShellStartBigProfilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ShellAddBigHoles(builder, bigHoles):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(bigHoles), 0
    )


def ShellStartBigHolesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ShellAddType(builder, type):
    builder.PrependInt8Slot(5, type, 0)


def ShellAddProfilesFaceIds(builder, profilesFaceIds):
    builder.PrependUOffsetTRelativeSlot(
        6, flatbuffers.number_types.UOffsetTFlags.py_type(profilesFaceIds), 0
    )


def ShellStartProfilesFaceIdsVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)


def ShellEnd(builder):
    return builder.EndObject()


class CircleExtrusion(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CircleExtrusion()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCircleExtrusion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def CircleExtrusionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # CircleExtrusion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CircleExtrusion
    def Radius(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8),
            )
        return 0

    # CircleExtrusion
    def RadiusAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # CircleExtrusion
    def RadiusLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CircleExtrusion
    def RadiusIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # CircleExtrusion
    def Axes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Axis()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CircleExtrusion
    def AxesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CircleExtrusion
    def AxesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0


def CircleExtrusionStart(builder):
    builder.StartObject(2)


def CircleExtrusionAddRadius(builder, radius):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(radius), 0
    )


def CircleExtrusionStartRadiusVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)


def CircleExtrusionAddAxes(builder, axes):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(axes), 0
    )


def CircleExtrusionStartAxesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def CircleExtrusionEnd(builder):
    return builder.EndObject()


class Meshes(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Meshes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeshes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def MeshesBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # Meshes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Meshes
    def Coordinates(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def MeshesItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Meshes
    def MeshesItemsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def MeshesItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def MeshesItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Meshes
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = Sample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Meshes
    def Representations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 32
            obj = Representation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def RepresentationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def RepresentationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Meshes
    def Materials(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 6
            obj = Material()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def MaterialsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def MaterialsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Meshes
    def CircleExtrusions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CircleExtrusion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def CircleExtrusionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def CircleExtrusionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Meshes
    def Shells(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Shell()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def ShellsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def ShellsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Meshes
    def LocalTransforms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 48
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def LocalTransformsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def LocalTransformsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Meshes
    def GlobalTransforms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 48
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def GlobalTransformsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def GlobalTransformsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # Meshes
    def MaterialIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Meshes
    def MaterialIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def MaterialIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def MaterialIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Meshes
    def RepresentationIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Meshes
    def RepresentationIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def RepresentationIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def RepresentationIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # Meshes
    def SampleIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Meshes
    def SampleIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def SampleIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def SampleIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # Meshes
    def LocalTransformIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Meshes
    def LocalTransformIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def LocalTransformIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def LocalTransformIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # Meshes
    def GlobalTransformIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Meshes
    def GlobalTransformIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def GlobalTransformIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def GlobalTransformIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0


def MeshesStart(builder):
    builder.StartObject(14)


def MeshesAddCoordinates(builder, coordinates):
    builder.PrependStructSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(coordinates), 0
    )


def MeshesAddMeshesItems(builder, meshesItems):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(meshesItems), 0
    )


def MeshesStartMeshesItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0
    )


def MeshesStartSamplesVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)


def MeshesAddRepresentations(builder, representations):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(representations), 0
    )


def MeshesStartRepresentationsVector(builder, numElems):
    return builder.StartVector(32, numElems, 4)


def MeshesAddMaterials(builder, materials):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(materials), 0
    )


def MeshesStartMaterialsVector(builder, numElems):
    return builder.StartVector(6, numElems, 1)


def MeshesAddCircleExtrusions(builder, circleExtrusions):
    builder.PrependUOffsetTRelativeSlot(
        5, flatbuffers.number_types.UOffsetTFlags.py_type(circleExtrusions), 0
    )


def MeshesStartCircleExtrusionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesAddShells(builder, shells):
    builder.PrependUOffsetTRelativeSlot(
        6, flatbuffers.number_types.UOffsetTFlags.py_type(shells), 0
    )


def MeshesStartShellsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesAddLocalTransforms(builder, localTransforms):
    builder.PrependUOffsetTRelativeSlot(
        7, flatbuffers.number_types.UOffsetTFlags.py_type(localTransforms), 0
    )


def MeshesStartLocalTransformsVector(builder, numElems):
    return builder.StartVector(48, numElems, 8)


def MeshesAddGlobalTransforms(builder, globalTransforms):
    builder.PrependUOffsetTRelativeSlot(
        8, flatbuffers.number_types.UOffsetTFlags.py_type(globalTransforms), 0
    )


def MeshesStartGlobalTransformsVector(builder, numElems):
    return builder.StartVector(48, numElems, 8)


def MeshesAddMaterialIds(builder, materialIds):
    builder.PrependUOffsetTRelativeSlot(
        9, flatbuffers.number_types.UOffsetTFlags.py_type(materialIds), 0
    )


def MeshesStartMaterialIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesAddRepresentationIds(builder, representationIds):
    builder.PrependUOffsetTRelativeSlot(
        10, flatbuffers.number_types.UOffsetTFlags.py_type(representationIds), 0
    )


def MeshesStartRepresentationIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesAddSampleIds(builder, sampleIds):
    builder.PrependUOffsetTRelativeSlot(
        11, flatbuffers.number_types.UOffsetTFlags.py_type(sampleIds), 0
    )


def MeshesStartSampleIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesAddLocalTransformIds(builder, localTransformIds):
    builder.PrependUOffsetTRelativeSlot(
        12, flatbuffers.number_types.UOffsetTFlags.py_type(localTransformIds), 0
    )


def MeshesStartLocalTransformIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesAddGlobalTransformIds(builder, globalTransformIds):
    builder.PrependUOffsetTRelativeSlot(
        13, flatbuffers.number_types.UOffsetTFlags.py_type(globalTransformIds), 0
    )


def MeshesStartGlobalTransformIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def MeshesEnd(builder):
    return builder.EndObject()


class Attribute(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Attribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # Attribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Attribute
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # Attribute
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Attribute
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def AttributeStart(builder):
    builder.StartObject(1)


def AttributeAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0
    )


def AttributeStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def AttributeEnd(builder):
    return builder.EndObject()


class Relation(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Relation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRelation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def RelationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # Relation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Relation
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # Relation
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Relation
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def RelationStart(builder):
    builder.StartObject(1)


def RelationAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0
    )


def RelationStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def RelationEnd(builder):
    return builder.EndObject()


class SpatialStructure(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpatialStructure()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpatialStructure(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def SpatialStructureBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # SpatialStructure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpatialStructure
    def LocalId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags, o + self._tab.Pos
            )
        return None

    # SpatialStructure
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialStructure
    def Children(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SpatialStructure()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SpatialStructure
    def ChildrenLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SpatialStructure
    def ChildrenIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0


def SpatialStructureStart(builder):
    builder.StartObject(3)


def SpatialStructureAddLocalId(builder, localId):
    builder.PrependUint32Slot(0, localId, None)


def SpatialStructureAddCategory(builder, category):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(category), 0
    )


def SpatialStructureAddChildren(builder, children):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(children), 0
    )


def SpatialStructureStartChildrenVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def SpatialStructureEnd(builder):
    return builder.EndObject()


class Model(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Model()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def ModelBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed
        )

    # Model
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Model
    def Metadata(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def Guids(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # Model
    def GuidsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def GuidsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Model
    def GuidsItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Model
    def GuidsItemsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Model
    def GuidsItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def GuidsItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Model
    def MaxLocalId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags, o + self._tab.Pos
            )
        return 0

    # Model
    def LocalIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Model
    def LocalIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Model
    def LocalIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def LocalIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Model
    def Categories(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # Model
    def CategoriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def CategoriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Model
    def Meshes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Meshes()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def Attributes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Attribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def AttributesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def AttributesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Model
    def Relations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Relation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def RelationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def RelationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # Model
    def RelationsItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Int32Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4),
            )
        return 0

    # Model
    def RelationsItemsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Model
    def RelationsItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def RelationsItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Model
    def Guid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def SpatialStructure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SpatialStructure()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def UniqueAttributes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # Model
    def UniqueAttributesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def UniqueAttributesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # Model
    def RelationNames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # Model
    def RelationNamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def RelationNamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0


def ModelStart(builder):
    builder.StartObject(14)


def ModelAddMetadata(builder, metadata):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0
    )


def ModelAddGuids(builder, guids):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(guids), 0
    )


def ModelStartGuidsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddGuidsItems(builder, guidsItems):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(guidsItems), 0
    )


def ModelStartGuidsItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddMaxLocalId(builder, maxLocalId):
    builder.PrependUint32Slot(3, maxLocalId, 0)


def ModelAddLocalIds(builder, localIds):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(localIds), 0
    )


def ModelStartLocalIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddCategories(builder, categories):
    builder.PrependUOffsetTRelativeSlot(
        5, flatbuffers.number_types.UOffsetTFlags.py_type(categories), 0
    )


def ModelStartCategoriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddMeshes(builder, meshes):
    builder.PrependUOffsetTRelativeSlot(
        6, flatbuffers.number_types.UOffsetTFlags.py_type(meshes), 0
    )


def ModelAddAttributes(builder, attributes):
    builder.PrependUOffsetTRelativeSlot(
        7, flatbuffers.number_types.UOffsetTFlags.py_type(attributes), 0
    )


def ModelStartAttributesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddRelations(builder, relations):
    builder.PrependUOffsetTRelativeSlot(
        8, flatbuffers.number_types.UOffsetTFlags.py_type(relations), 0
    )


def ModelStartRelationsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddRelationsItems(builder, relationsItems):
    builder.PrependUOffsetTRelativeSlot(
        9, flatbuffers.number_types.UOffsetTFlags.py_type(relationsItems), 0
    )


def ModelStartRelationsItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddGuid(builder, guid):
    builder.PrependUOffsetTRelativeSlot(
        10, flatbuffers.number_types.UOffsetTFlags.py_type(guid), 0
    )


def ModelAddSpatialStructure(builder, spatialStructure):
    builder.PrependUOffsetTRelativeSlot(
        11, flatbuffers.number_types.UOffsetTFlags.py_type(spatialStructure), 0
    )


def ModelAddUniqueAttributes(builder, uniqueAttributes):
    builder.PrependUOffsetTRelativeSlot(
        12, flatbuffers.number_types.UOffsetTFlags.py_type(uniqueAttributes), 0
    )


def ModelStartUniqueAttributesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelAddRelationNames(builder, relationNames):
    builder.PrependUOffsetTRelativeSlot(
        13, flatbuffers.number_types.UOffsetTFlags.py_type(relationNames), 0
    )


def ModelStartRelationNamesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def ModelEnd(builder):
    return builder.EndObject()
